org: jsparvath # Sign up on https://serverless.com/dashboard/ if you don't already have a tenant
app: my-app # create/add app on dashboard.serverless.com

service: all-services

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  region: eu-west-2
  stage: ${opt:stage, 'dev'} # Use 'sls deploy --stage prod' for deploying to production

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

plugins:
  - serverless-webpack
