service: postapp-database

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  # Set the table name here so we can use it while testing locally
  postsTable: ${self:custom.stage}-postapp-postsTable

provider:
  name: aws
  stage: dev
  region: us-east-1

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Generate a name based on the stage
        TableName: ${self:custom.postsTable}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: postId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: postId
            KeyType: RANGE
        # Set the capacity to auto-scale
        BillingMode: PAY_PER_REQUEST

  Outputs:
    PostsTableArn:
      Value:
        Fn::GetAtt:
          - PostsTable
          - Arn
      Export:
        Name: ${self:custom.stage}-PostsTableArn
