service: postapp-billing-api

plugins:
  - serverless-webpack

custom:
  stage: ${self:provider.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'} # Use 'sls deploy --stage prod' for deploying to production
  region: us-east-1
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.stage}-ExtApiGatewayApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.stage}-ExtApiGatewayApiRootResourceId

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    stage: ${self:custom.stage}

functions:
  # Defines an HTTP API endpoint that calls the main function in billing.js
  # - path: url path is /billing
  # - method: POST request
  billing:
    handler: handler.main
    events:
      - http:
          path: billing
          method: get
          cors: true
